src/Entity/FOSUserBundle/User.php
<?php
// src/Entity/User.php

namespace App\Entity\FOSUserBundle;

use App\Entity\Commentaire;
use App\Entity\Profile;
use App\Entity\Sortie;
use Doctrine\Common\Collections\Collection;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="fos_user")
 *  @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap( {"usersimple" = "UserSimple", "user" = "User"} )
 * 
 */
 class User extends BaseUser
                     {
                     
                         /**
                          * @ORM\Id
                         * @ORM\Column(type="integer")
                         * @ORM\GeneratedValue(strategy="AUTO")
                         */
                         protected $id;
                         /**
                          *  @ORM\Column(name="sexe",type="string", nullable=true)
                         *  @Assert\NotBlank()
                         */
                         protected $sexe;
                     
                         /**
                          *  @ORM\Column(name="prenom",type="string", nullable=true)
                         *  @Assert\NotBlank()
                         */
                         protected $prenom;
                     
                         
                         /**
                          *  @ORM\Column(name="date_birth",type="datetime", nullable=true)
                         *  @Assert\NotBlank()
                         *  @Assert\DateTime()
                         */
                         protected $dateBirth;
                     
                         /**
                          * @ORM\OneToOne(targetEntity="App\Entity\Profile", cascade={"persist"})
                         * @ORM\JoinColumn(name="profile_id", referencedColumnName="id")
                         */
                         protected $profile;
                     
                         /**
                          *  @ORM\Column(name="date_inscription",type="datetime", nullable=true)
                         *  @Assert\NotBlank()
                         *  @Assert\DateTime()
                         */
                         protected $dateInscription;
                     
                         /**
                          * @ORM\OneToMany(targetEntity="App\Entity\Sortie", mappedBy="organisateur")
                          */
                         private $sorties;
                     
                         /**
                         *  @ORM\Column(name="last_activity",type="datetime", nullable=true)
                         *  @Assert\DateTime()
                         */
                         protected $lastActivity;
            
                         /**
                          * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="auteur", orphanRemoval=true)
                          */
                         private $commentaires;
                     
                         public function __construct()
                         {
                             parent::__construct();
                             $this->dateInscription= new \DateTime('now',new \DateTimeZone('Europe/Paris'));
                             $this->sorties = new ArrayCollection();
                             $this->commentaires = new ArrayCollection();
                         }
                         
                         /**
                          * @return \DateTime
                         */
                         public function getDateInscription()
                         {
                             return $this->dateInscription;
                         }
                     
                         public function getSexe()
                         {
                             return $this->sexe;
                         }
                     
                         public function setSexe(string $sexe)
                         {
                             $this->sexe = $sexe;
                     
                             return $this;
                         }
                         /**
                          * @return boolean
                         */
                         public function isHomme(){
                             return $this->sexe === "H";
                         }
                     
                         /**
                          * @return string
                         */
                         public function getPrenom()
                         {
                             return $this->prenom;
                         }
                         /**
                          * @param string
                         */
                         public function setPrenom(string $prenom)
                         {
                             $this->prenom = $prenom;
                     
                             return $this;
                         }
                     
                     
                         /**
                          * Get the value of dateBirth
                         */ 
                         public function getDateBirth()
                         {
                             return $this->dateBirth;
                         }
                     
                         /**
                          * Set the value of dateBirth
                         *
                         * @return  self
                         */ 
                         public function setDateBirth($dateBirth)
                         {
                             $this->dateBirth = $dateBirth;
                             return $this;
                         }
                     
                         public function getAge(): ?int
                         {
                             $date_naissance=$this->getDateBirth();
                             $today=new \DateTime();
                             $diff= $date_naissance->diff($today);
                             $annees= intval($diff->format("%Y"));
                             return $annees;
                         }
                         public function isMajeur() : bool
                         {
                             return $this->getAge()>=18;
                         }
                     
                         /**
                          * @Assert\Callback
                         */
                         public function validate(ExecutionContextInterface $context, $payload)
                         {
                             if (!$this->isMajeur() ) {
                                 $context->buildViolation('Vous devez etre majeur pour vous incrire.')
                                     ->atPath('dateBirth')
                                     ->addViolation();
                             }
                             if(!preg_match("((?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,})",$this->getPlainPassword())){
                                 $context->buildViolation('Votre mot de passe doit contenir au moins 8 caractères alpha numeriques (chiffre + minuscule + majuscule)')
                                 ->atPath('plainPassword')
                                 ->addViolation();
                             }
                             //plainPassword  ((?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,})
                         }
                     
                     
                         public function getProfile(): ?Profile
                         {
                             return $this->profile;
                         }
                     
                         public function setProfile(?Profile $profile): self
                         {
                             $this->profile = $profile;
                     
                             return $this;
                         }
                     
                     
                         /**
                      * @return Collection|Sortie[]
                      */
                     public function getSorties(): ArrayCollection
                     {
                         return $this->sorties;
                     }
                     
                     public function addSorty(Sortie $sorty): self
                     {
                         if (!$this->sorties->contains($sorty)) {
                             $this->sorties[] = $sorty;
                            // $sorty->setTypeSortie($this);
                         }
                     
                         return $this;
                     }
                     
                     public function removeSorty(Sortie $sorty): self
                     {
                         if ($this->sorties->contains($sorty)) {
                             $this->sorties->removeElement($sorty);
                             // set the owning side to null (unless already changed)
                             if ($sorty->getTypeSortie() === $this) {
                                 $sorty->setTypeSortie(null);
                             }
                         }
                     
                         return $this;
                     }
                     
                         /**
                          * Get the value of lastActivity
                          */ 
                         public function getLastActivity() :?\DateTime
                         {

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\SortieRepository;
use App\Entity\FOSUserBundle\User;
use Symfony\Component\HttpFoundation\File\Exception\AccessDeniedException;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(SortieRepository $sortieRepository)
    {

    
        $breadcrumb=["index"=>"Accueil"];
        return $this->render('default/index.html.twig',['sorties' => $sortieRepository->getSortiesAccueil(),"breadcrumb"=>$breadcrumb ]);
    }

    /**
     * @Route("/pulse", name="pulse")
     */
    public function pulse()
    {
        $breadcrumb=["index"=>"Accueil","pulse"=>"pulse"];
        return $this->render('default/pulse.html.twig',compact("breadcrumb"));
    }

      /**
     * @Route("/show/profile/{id}", name="default_show_profile", requirements={"id"="\d+"})
     */
    public function showProfile(User $user)
    {

        $this->denyAccessUnlessGranted('ROLE_USER');

        $breadcrumb=["index"=>"Accueil",""=>"Profile ".$user->getUsername()];
        return $this->render('default/show_profile.html.twig',compact("breadcrumb","user"));
    }

      /**
     * @Route("/logintest", name="logintest")
     */
    public function logintest()
    {

     
        return $this->render('login.html.twig');
    }
     /**
     * @Route("/pricingtest", name="logintest")
     */
    public function pricingtest()
    {

     
        return $this->render('princing_table.html.twig');
    }
}

templates/default/index.html.twig
{% extends 'main.html.twig' %}

{% block title %}{{parent()}} Accueil{% endblock %}


{% block side_bar_left %}
{{ render(controller('App\\Controller\\SideBarLeftController::index' )) }}
 
{% endblock side_bar_left %}

{% block content_main %}

<div class="accordion" id="accordionExample2">
     <div class="card">
          <div class="card-header" id="headingTwo">
               <h5 class="mb-0">
               <button class="btn btn-link " type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                    Sorties   
              {% if app.user %}
               </button> <a class="btn btn-outline-success btn-sm "href="{{ path('sortie_new') }}">Créer sortie <i class="fa fa-plus" aria-hidden="true"></i></a>
               {% endif %}
               </h5> 
          </div>
    <div id="collapseTwo" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordionExample2">
      <div class="card-body">
        <table class="table table-sm" style="text-align: center;">
          <thead>
         
          </thead>
          <tbody>

           {% for year in sorties %}
             <tr>
                      <th colspan="2" scope="col">Date</th>
                    <th colspan="3" scope="col">intitulé</th>
                    <th scope="col">Participants</th>
                      <th scope="col">Organisateur</th>
          
                </tr>
              {% for mois,jours in year %}
                  <tr class="table-primary" ><th colspan="7"style ="font-size:20px;	font-weight: bolder;" >{{mois}} </th></tr>  
                      {% for jour,sorties in jours %}
                        <tr align="left"  class="table-light"><th colspan="7" >{{jour}}</th></tr>
                              {% for sortie in sorties %}
                                <tr {% if not isSortieModifiable(sortie.id) %}class="table-secondary" {% else %} class="" {% endif %} >
                                <td>&nbsp;</td>
                                    <th style= "font-weight: lighter;">{{sortie.heureSortie}}</th>
                                    <td colspan="3" ><a href="{{ path('sortie_show', {'id': sortie.id}) }}">{{sortie.intitule}}</a></td>
                                    <td>{{'1/'~ sortie.nbPersonneMax}}</td>
                                    <td ><a class="pseudo-{{sortie.sexe}}" href="{{ path('default_show_profile', {'id': sortie.organisateur}) }}">{{sortie.username}}</a></td>
                                </tr>
                              {% endfor %}
                        
                      {% endfor %}
              {% endfor %}
         {% else %}
            <tr>
                <td colspan="2">Aucune sortie</td>
            </tr>
        {% endfor %}
          </tbody>
     </table> 
      </div>
    </div>
  </div>
</div>


{% endblock content_main %}

{% block side_bar_right %}
  {{ render(controller('App\\Controller\\SideBarRightController::index' )) }}
{% endblock side_bar_right %}


{% block javascripts %}
     <script src="{{ asset('js/datepicker.js') }}"></script>
{% endblock javascripts %}

templates/default/show_profile.html.twig
{% extends "layout.html.twig" %}
    {% block stylesheets %}
     <link rel="stylesheet" href="{{ asset('css/profile.css') }}">
    {% endblock stylesheets %}  


{% block fos_user_content %}
<div class="jumbotron">
{% include "default/show_profile_content.html.twig" %}
</div>

{% include "default/show_profile_content2.html.twig" %}



{% endblock fos_user_content %}

 {% block javascripts %}
          <script src="{{ asset('js/select2.js') }}"></script>
  
 {% endblock javascripts %}

templates/default/show_profile_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}


<div class="fos_user_user_show">
  <div class="card border-secondary mb-3 card-profile" >
    <div class="card-header">
        <h3 class="card-title">
            <span class="badge badge-pill badge-{{user.sexe}}">
                {{ user.username }}
            </span>
              {% if isUserProfile(user, app.user) %}
                <a href="{{path('profile') }}" class="btn btn-outline-success">Modifier mon profile</a>
              {% endif %}
          <!--  <span class="float-right">Inscrit{{user.sexe == "F"?"e":""}} depuis le {{ user.dateInscription|localizeddate('none', 'none', null, null, 'dd MMMM ') }}</span> -->
          <span class="float-right">Inscrit{{user.sexe == "F"?"e":""}} depuis le {{ user.dateInscription|date( 'd-M-Y') }}</span>
        </h3>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-6">
          <p class="text-center">
            {% if user.profile.photo %}
              <img style="max-height: 200px;min-height: 115px;max-width:438px;min-width:250px;"  id="photo_profil" src="{{asset('uploads/profilePhoto/'~ user.profile.photo)}}" alt="photo de profil">
            {% else %}
               <img style="max-height: 200px;min-height: 115px;max-width:438px;min-width:250px;"  id="photo_profil" src="{{asset('uploads/profilePhoto/Default2-'~ user.sexe ~'.jpg')}}" alt="photo de profil">
            {% endif %} 
          </p>
        </div>
        <div class="col-md-6">
            <p class="card-text">
                <p><i class="fab fa-teamspeak"></i> Description </p> 
                <p><span id="show-description">{{ user.profile.description |nl2br  }}</span><p>
              </p>
        </div>
        
      </div>  
      
      <div class="row">
          <div class=" col-md-6">
              {% if user.isHomme %}
              <p class="card-text"><i class="fas fa-male"></i> {{ user.prenom }}</p>
              {% else %}
               <p class="card-text"><i class="fas fa-female"></i> {{ user.prenom }}</p>
              {% endif %}
             <!-- <p><i class="fas fa-birthday-cake"></i> {{user.dateBirth|localizeddate('none', 'none', null, null, 'EEEE dd MMMM')}} ({{user.age}} ans)</p> -->
             <p><i class="fas fa-birthday-cake"></i> {{user.dateBirth|date('d-M-Y')}} ({{user.age}} ans)</p>
             
            
          </div>
          <div class="col-md-6">
              <p class="card-text">
                <i class="fas fa-heartbeat"></i>
                <span id="show-situation">Situation : {{ user.profile.situation }}</span>
              </p>
              <p>
                <i class="fas fa-map-marker-alt"></i> 
                <span id="show-departement">Departement : {{ user.profile.departement.nom }}</span>  
              </p>
              
          </div>
      </div>
  </div>
</div>

templates/default/show_profile_content2.html.twig
<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog" alt=""/>
                            <div class="file btn btn-lg btn-primary">
                                Change Photo
                                <input type="file" name="file"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                        Kshiti Ghelani
                                    </h5>
                                    <h6>
                                        Web Developer and Designer
                                    </h6>
                                    <p class="proile-rating">RANKINGS : <span>8/10</span></p>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link" id="home-tab2" data-toggle="tab" tada-target="#home2" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="profile-tab2" data-toggle="tab" data-target="#profile2" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <input type="submit" class="profile-edit-btn" name="btnAddMore" value="Edit Profile"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <p>WORK LINK</p>
                            <a href="">Website Link</a><br/>
                            <a href="">Bootsnipp Profile</a><br/>
                            <a href="">Bootply Profile</a>
                            <p>SKILLS</p>
                            <a href="">Web Designer</a><br/>
                            <a href="">Web Developer</a><br/>
                            <a href="">WordPress</a><br/>
                            <a href="">WooCommerce</a><br/>
                            <a href="">PHP, .Net</a><br/>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home2" role="tabpanel" aria-labelledby="home-tab2">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>User Id</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Kshiti123</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Name</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Kshiti Ghelani</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>kshitighelani@gmail.com</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Phone</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>123 456 7890</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Profession</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Web Developer and Designer</p>
                                            </div>
                                        </div>
                            </div>
                            <div class="tab-pane fade" id="profile2" role="tabpanel" aria-labelledby="profile-tab2">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Experience</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Expert</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Hourly Rate</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>10$/hr</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Total Projects</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>230</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>English Level</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Expert</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Availability</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>6 months</p>
                                            </div>
                                        </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <label>Your Bio</label><br/>
                                        <p>Your detail description</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>           
        </div>